### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by DrewRidley** [iDevelopThings/SurrealDB-Explorer#1]
Does this explorer support https?

I use the same credentials and they work fine on surrealist but for surrealdb explorer it simply says invalid connection. I am using https for my server and thought maybe that's the cause? If I use valid credentials it doesn't show an error but also doesn't do anything, just shows the loading wheel for a short time.

**Comment by iDevelopThings** [comment]
I will try look into this asap, just a bit busy over this weekend, it's likely cause of https yeah - I made it under the assumption that everyone would use their local non-secure server, bit of an oversight on my behalf 😅

**Comment by iDevelopThings** [comment]
@DrewRidley So I'm going to do a release shortly - I couldn't figure out this problem you have specifically - I thought I had some special logic for connection urls, but turns out i didn't(must have got confused with some other project)

But i made some slight adjustments to the connect error handling and temp removed the thing that causes the "invalid connection" validation, it's probably pointless anyway^^

**Comment by iDevelopThings** [comment]
Okay give this release a go: https://github.com/iDevelopThings/SurrealDB-Explorer/releases/tag/v0.0.5

And please let me know if it's sorted or not; 

To clarify also; Was your URL starting with ws/wss?

If not, can you give me the host you're trying to connect with so I can see if it's something else?
